### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by Valiuhaaa** [DmytroKorniienko/FireLamp_EmbUI#104]
Доброго дня. Допоможіть з прикладом mqtt команди. Наприклад: яку выдправити команду, щоб змінити ефект?

**Comment by DmytroKorniienko** [comment]
Усі доступні команди можете переглянути в файлі: https://github.com/DmytroKorniienko/FireLamp_EmbUI/blob/master/include/effects_types.h , команду відправляти в топік /set

**Comment by Valiuhaaa** [comment]
Не виходить. Щось роблю не так. Намагаюсь выдправити команди за допомогою MQTT explorer
![Screenshot_5](https://user-images.githubusercontent.com/75776835/194752731-624157ab-9d15-4231-b02e-0318878e9c29.png)
![Screenshot_4](https://user-images.githubusercontent.com/75776835/194752732-891b918e-b98f-4e31-b3c1-39f95b1fd25c.png)

**Comment by DmytroKorniienko** [comment]
> Не виходить.
![image](https://user-images.githubusercontent.com/26786760/194958361-f76a7ccf-04c7-41d8-b09a-4531eafad5fe.png)
![image](https://user-images.githubusercontent.com/26786760/194958468-96f121a2-de45-4974-b0ba-183bc4669a86.png)
![image](https://user-images.githubusercontent.com/26786760/194958550-3c88bb78-e73f-46de-a1e9-785ee9b4c5d7.png)
