### ISSUE TITLE
class ArduinoJson6200_F1::JsonArray' has no member named 'getElement

### ISSUE THREAD

**Issue by mihasybn** [DmytroKorniienko/FireLamp_EmbUI#112]
[{
	"resource": "/c:/FireLamp_EmbUI-master/.pio/libdeps/esp32/EmbUI/src/ui.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'class ArduinoJson6200_F1::JsonArray' has no member named 'getElement'",
	"startLineNumber": 103,
	"startColumn": 40,
	"endLineNumber": 103,
	"endColumn": 40
}]
[{
	"resource": "/c:/FireLamp_EmbUI-master/.pio/libdeps/esp32/EmbUI/src/ui.cpp",
	"owner": "C/C++",
	"code": "135",
	"severity": 8,
	"message": "класс \"ArduinoJson6200_F1::JsonArray\" не содержит члена \"getElement\"",
	"source": "C/C++",
	"startLineNumber": 103,
	"startColumn": 40,
	"endLineNumber": 103,
	"endColumn": 50
}]
[{
	"resource": "/c:/FireLamp_EmbUI-master/.pio/libdeps/esp32/EmbUI/src/ui.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'class ArduinoJson6200_F1::JsonArray' has no member named 'getElement'",
	"startLineNumber": 107,
	"startColumn": 94,
	"endLineNumber": 107,
	"endColumn": 94
}]
[{
	"resource": "/c:/FireLamp_EmbUI-master/.pio/libdeps/esp32/EmbUI/src/ui.cpp",
	"owner": "C/C++",
	"code": "135",
	"severity": 8,
	"message": "класс \"ArduinoJson6200_F1::JsonArray\" не содержит члена \"getElement\"",
	"source": "C/C++",
	"startLineNumber": 107,
	"startColumn": 94,
	"endLineNumber": 107,
	"endColumn": 104
}]
Слава Україні!
Допоможіть. Я зовсім не програміст.
Я так зрозумів, що getElement видалили с ArduinoJson. А як змінити код не розумію. 
Дякую.

**Comment by kostyamat** [comment]
Вітаю. Героям слава! Тимчасове рішення - в platformio.ini строки з https://github.com/DmytroKorniienko/EmbUI.git#2.7.0 замініть на https://github.com/DmytroKorniienko/EmbUI.git#dev

**Comment by mihasybn** [comment]
Велике дякую. У понеділок спробую.

пт, 13 янв. 2023 г., 19:42 Kostyantyn Matviyevskyy ***@***.***

**Comment by kostyamat** [comment]
Не забудьте після заміни рядків видалити з проекту парку .pio
