### ISSUE TITLE
Как с браузером управлять?

### ISSUE THREAD

**Issue by Vaqtincha** [DmytroKorniienko/FireLamp_EmbUI#122]
С андроида. Пробовал скачать service browser он висит в загрузке. Также пробовал зайти на ип который получаю при подключении ап (у меня 192.168.4.2) не заходит.
На странице проекта говорится про http://esp-xxxxxx/cmd?arg=param
Но незнаю откуда взять xxxxxx

**Comment by DmytroKorniienko** [comment]
Why you trying 192.168.4.2? Default IP for AP mode is: 192.168.4.1.

**Comment by Vaqtincha** [comment]
@DmytroKorniienko 

"При загрузке веб-страницы https://192.168.4.1/ произошла ошибка по следующим причинам:

net::ERR_CONNECTION_REFUSED"

Разницы нет. Все равно не подключается

**Comment by Vaqtincha** [comment]
Браузер сам вставить что хочет я просто вводил 192.168.4.1

**Comment by 80Stepko08** [comment]
Use http://192.168.4.1/

**Comment by Vaqtincha** [comment]
@80Stepko08 ситуация изменилась! Теперь просто открывается страница белым фоном и надписью "Not found"

**Comment by Vaqtincha** [comment]
FireLamp-7E87CEB6721C вот таг ссид генерирует без пароля.

**Comment by 80Stepko08** [comment]
> @80Stepko08 ситуация изменилась! Теперь просто открывается страница белым фоном и надписью "Not found"

You've forgot about flashing FileSystem image

**Comment by Vaqtincha** [comment]
Пардон. Использую platdormio и не вижу этого файла littlefs.bin как его получить и прошить? На readme мало информации.

**Comment by 80Stepko08** [comment]
![image](https://github.com/DmytroKorniienko/FireLamp_EmbUI/assets/26786944/d6ba38f6-1aad-407f-8aac-734b46ec2c63)
